repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: pipenv run ruff check --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff-format
        entry: pipenv run ruff format
        language: system
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: pipenv run mypy
        language: system
        types_or: [python, pyi]
        pass_filenames: false
        require_serial: true
